//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var GameMode = &struct {
	Author postgres.StringExpression
	Gold   postgres.StringExpression
	Custom postgres.StringExpression
}{
	Author: postgres.NewEnumValue("author"),
	Gold:   postgres.NewEnumValue("gold"),
	Custom: postgres.NewEnumValue("custom"),
}
