run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam

issues:
  exclude-dirs:
    - db/.gen
