//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type GameMode string

const (
	GameMode_Author GameMode = "author"
	GameMode_Gold   GameMode = "gold"
	GameMode_Custom GameMode = "custom"
)

var GameModeAllValues = []GameMode{
	GameMode_Author,
	GameMode_Gold,
	GameMode_Custom,
}

func (e *GameMode) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "author":
		*e = GameMode_Author
	case "gold":
		*e = GameMode_Gold
	case "custom":
		*e = GameMode_Custom
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for GameMode enum")
	}

	return nil
}

func (e GameMode) String() string {
	return string(e)
}
