//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Scores struct {
	ID            uuid.UUID `sql:"primary_key"`
	PlayerID      uuid.UUID
	GameMode      GameMode
	Score         int32
	MapsCompleted int32
	MapsSkipped   int32
	DurationMs    int32
	Metadata      *string
	CreatedAt     *time.Time
}
