//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var BannedPlayers = newBannedPlayersTable("public", "banned_players", "")

type bannedPlayersTable struct {
	postgres.Table

	// Columns
	ID       postgres.ColumnString
	PlayerID postgres.ColumnString
	Reason   postgres.ColumnString
	BannedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BannedPlayersTable struct {
	bannedPlayersTable

	EXCLUDED bannedPlayersTable
}

// AS creates new BannedPlayersTable with assigned alias
func (a BannedPlayersTable) AS(alias string) *BannedPlayersTable {
	return newBannedPlayersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BannedPlayersTable with assigned schema name
func (a BannedPlayersTable) FromSchema(schemaName string) *BannedPlayersTable {
	return newBannedPlayersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BannedPlayersTable with assigned table prefix
func (a BannedPlayersTable) WithPrefix(prefix string) *BannedPlayersTable {
	return newBannedPlayersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BannedPlayersTable with assigned table suffix
func (a BannedPlayersTable) WithSuffix(suffix string) *BannedPlayersTable {
	return newBannedPlayersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBannedPlayersTable(schemaName, tableName, alias string) *BannedPlayersTable {
	return &BannedPlayersTable{
		bannedPlayersTable: newBannedPlayersTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newBannedPlayersTableImpl("", "excluded", ""),
	}
}

func newBannedPlayersTableImpl(schemaName, tableName, alias string) bannedPlayersTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		PlayerIDColumn = postgres.StringColumn("player_id")
		ReasonColumn   = postgres.StringColumn("reason")
		BannedAtColumn = postgres.TimestampzColumn("banned_at")
		allColumns     = postgres.ColumnList{IDColumn, PlayerIDColumn, ReasonColumn, BannedAtColumn}
		mutableColumns = postgres.ColumnList{PlayerIDColumn, ReasonColumn, BannedAtColumn}
		defaultColumns = postgres.ColumnList{IDColumn, BannedAtColumn}
	)

	return bannedPlayersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		PlayerID: PlayerIDColumn,
		Reason:   ReasonColumn,
		BannedAt: BannedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
