//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Metrics = newMetricsTable("public", "metrics", "")

type metricsTable struct {
	postgres.Table

	// Columns
	ID    postgres.ColumnString
	Name  postgres.ColumnString
	Count postgres.ColumnInteger
	Date  postgres.ColumnDate

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MetricsTable struct {
	metricsTable

	EXCLUDED metricsTable
}

// AS creates new MetricsTable with assigned alias
func (a MetricsTable) AS(alias string) *MetricsTable {
	return newMetricsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MetricsTable with assigned schema name
func (a MetricsTable) FromSchema(schemaName string) *MetricsTable {
	return newMetricsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MetricsTable with assigned table prefix
func (a MetricsTable) WithPrefix(prefix string) *MetricsTable {
	return newMetricsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MetricsTable with assigned table suffix
func (a MetricsTable) WithSuffix(suffix string) *MetricsTable {
	return newMetricsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMetricsTable(schemaName, tableName, alias string) *MetricsTable {
	return &MetricsTable{
		metricsTable: newMetricsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newMetricsTableImpl("", "excluded", ""),
	}
}

func newMetricsTableImpl(schemaName, tableName, alias string) metricsTable {
	var (
		IDColumn       = postgres.StringColumn("id")
		NameColumn     = postgres.StringColumn("name")
		CountColumn    = postgres.IntegerColumn("count")
		DateColumn     = postgres.DateColumn("date")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn, CountColumn, DateColumn}
		mutableColumns = postgres.ColumnList{NameColumn, CountColumn, DateColumn}
		defaultColumns = postgres.ColumnList{IDColumn, CountColumn, DateColumn}
	)

	return metricsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:    IDColumn,
		Name:  NameColumn,
		Count: CountColumn,
		Date:  DateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
