//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Players = newPlayersTable("public", "players", "")

type playersTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	OpenplanetID postgres.ColumnString
	DisplayName  postgres.ColumnString
	CreatedAt    postgres.ColumnTimestampz
	UpdatedAt    postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PlayersTable struct {
	playersTable

	EXCLUDED playersTable
}

// AS creates new PlayersTable with assigned alias
func (a PlayersTable) AS(alias string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PlayersTable with assigned schema name
func (a PlayersTable) FromSchema(schemaName string) *PlayersTable {
	return newPlayersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PlayersTable with assigned table prefix
func (a PlayersTable) WithPrefix(prefix string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PlayersTable with assigned table suffix
func (a PlayersTable) WithSuffix(suffix string) *PlayersTable {
	return newPlayersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPlayersTable(schemaName, tableName, alias string) *PlayersTable {
	return &PlayersTable{
		playersTable: newPlayersTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPlayersTableImpl("", "excluded", ""),
	}
}

func newPlayersTableImpl(schemaName, tableName, alias string) playersTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		OpenplanetIDColumn = postgres.StringColumn("openplanet_id")
		DisplayNameColumn  = postgres.StringColumn("display_name")
		CreatedAtColumn    = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampzColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, OpenplanetIDColumn, DisplayNameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{OpenplanetIDColumn, DisplayNameColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return playersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		OpenplanetID: OpenplanetIDColumn,
		DisplayName:  DisplayNameColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
