//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Scores = newScoresTable("public", "scores", "")

type scoresTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	PlayerID      postgres.ColumnString
	GameMode      postgres.ColumnString
	Score         postgres.ColumnInteger
	MapsCompleted postgres.ColumnInteger
	MapsSkipped   postgres.ColumnInteger
	DurationMs    postgres.ColumnInteger
	Metadata      postgres.ColumnString
	CreatedAt     postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScoresTable struct {
	scoresTable

	EXCLUDED scoresTable
}

// AS creates new ScoresTable with assigned alias
func (a ScoresTable) AS(alias string) *ScoresTable {
	return newScoresTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScoresTable with assigned schema name
func (a ScoresTable) FromSchema(schemaName string) *ScoresTable {
	return newScoresTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScoresTable with assigned table prefix
func (a ScoresTable) WithPrefix(prefix string) *ScoresTable {
	return newScoresTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScoresTable with assigned table suffix
func (a ScoresTable) WithSuffix(suffix string) *ScoresTable {
	return newScoresTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScoresTable(schemaName, tableName, alias string) *ScoresTable {
	return &ScoresTable{
		scoresTable: newScoresTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newScoresTableImpl("", "excluded", ""),
	}
}

func newScoresTableImpl(schemaName, tableName, alias string) scoresTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		PlayerIDColumn      = postgres.StringColumn("player_id")
		GameModeColumn      = postgres.StringColumn("game_mode")
		ScoreColumn         = postgres.IntegerColumn("score")
		MapsCompletedColumn = postgres.IntegerColumn("maps_completed")
		MapsSkippedColumn   = postgres.IntegerColumn("maps_skipped")
		DurationMsColumn    = postgres.IntegerColumn("duration_ms")
		MetadataColumn      = postgres.StringColumn("metadata")
		CreatedAtColumn     = postgres.TimestampzColumn("created_at")
		allColumns          = postgres.ColumnList{IDColumn, PlayerIDColumn, GameModeColumn, ScoreColumn, MapsCompletedColumn, MapsSkippedColumn, DurationMsColumn, MetadataColumn, CreatedAtColumn}
		mutableColumns      = postgres.ColumnList{PlayerIDColumn, GameModeColumn, ScoreColumn, MapsCompletedColumn, MapsSkippedColumn, DurationMsColumn, MetadataColumn, CreatedAtColumn}
		defaultColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return scoresTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		PlayerID:      PlayerIDColumn,
		GameMode:      GameModeColumn,
		Score:         ScoreColumn,
		MapsCompleted: MapsCompletedColumn,
		MapsSkipped:   MapsSkippedColumn,
		DurationMs:    DurationMsColumn,
		Metadata:      MetadataColumn,
		CreatedAt:     CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
